# This is a basic workflow to help you get started with Actions

name: update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '10 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Go environment
      uses: actions/setup-go@v1
      with:
        go-version: '1.14.4'
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        GIT_ASKPASS: './.git-askpass'
    - run: |
        go run main.go
        git config --global user.email '68090512+dthorsen-bot@users.noreply.github.com'
        git config --global user.name 'dthorsen-bot'
        git config --global credential.https://github.com.username dthorsen-bot
        git add blocklist.txt
        if git commit -m 'updated blocklist.txt'
        then
          git push origin master
        else
          echo "source blocklist was unchanged"
        fi
